# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# ==========================================
# CATS vs DOGS CLASSIFICATION USING SVM
# SkillCraft Technology Internship Task
# ==========================================

# Upload ZIP Dataset First
from google.colab import files
uploaded = files.upload()

# ------------------------------------------
# Extract ZIP File
# ------------------------------------------
import zipfile
import os

zip_file = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

print("Dataset Extracted Successfully!")

# ------------------------------------------
# Find Dataset Paths
# ------------------------------------------
for root, dirs, files_ in os.walk('/content/dataset'):
    if len(files_) > 0:
        print(root)

# Change these paths if your folder names differ
cat_path = "/content/dataset/PetImages/Cat"
dog_path = "/content/dataset/PetImages/Dog"

# ------------------------------------------
# Import Libraries
# ------------------------------------------
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# ------------------------------------------
# Load Images
# ------------------------------------------
images = []
labels = []
original_images = []

IMG_SIZE = 64

# Load Cat Images
count = 0
for img_name in os.listdir(cat_path):

    if count >= 1000:   # Use 1000 cat images
        break

    img_path = os.path.join(cat_path, img_name)

    try:
        img = cv2.imread(img_path)

        if img is None:
            continue

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        original_images.append(
            cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        )

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        images.append(gray.flatten())
        labels.append(0)   # Cat

        count += 1

    except:
        pass

# Load Dog Images
count = 0
for img_name in os.listdir(dog_path):

    if count >= 1000:   # Use 1000 dog images
        break

    img_path = os.path.join(dog_path, img_name)

    try:
        img = cv2.imread(img_path)

        if img is None:
            continue

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        original_images.append(
            cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        )

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        images.append(gray.flatten())
        labels.append(1)   # Dog

        count += 1

    except:
        pass

# ------------------------------------------
# Convert to NumPy Arrays
# ------------------------------------------
X = np.array(images)
y = np.array(labels)

print("Dataset Shape:", X.shape)

# ------------------------------------------
# Split Dataset
# ------------------------------------------
X_train, X_test, y_train, y_test, img_train, img_test = train_test_split(
    X,
    y,
    original_images,
    test_size=0.2,
    random_state=42
)

# ------------------------------------------
# Feature Scaling
# ------------------------------------------
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ------------------------------------------
# Train SVM Model
# ------------------------------------------
svm = SVC(
    kernel='linear',
    C=1
)

print("Training SVM...")
svm.fit(X_train, y_train)

# ------------------------------------------
# Predictions
# ------------------------------------------
predictions = svm.predict(X_test)

# ------------------------------------------
# Evaluation
# ------------------------------------------
accuracy = accuracy_score(y_test, predictions)

print("\nAccuracy:", accuracy)

print("\nClassification Report:\n")
print(classification_report(y_test, predictions))

# ------------------------------------------
# Display Actual Images with Predictions
# ------------------------------------------
plt.figure(figsize=(15,8))

for i in range(10):

    idx = random.randint(0, len(X_test)-1)

    plt.subplot(2,5,i+1)

    plt.imshow(img_test[idx])

    pred = "Dog" if predictions[idx] == 1 else "Cat"
    actual = "Dog" if y_test[idx] == 1 else "Cat"

    plt.title(f"Pred: {pred}\nActual: {actual}")

    plt.axis("off")

plt.tight_layout()
plt.show()

# ------------------------------------------
# Predict New Image
# ------------------------------------------
print("\nUpload a new image for prediction")

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

img = cv2.imread(file_name)

img = cv2.resize(img, (64,64))

display_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

sample = gray.flatten().reshape(1,-1)

sample = scaler.transform(sample)

prediction = svm.predict(sample)

plt.figure(figsize=(4,4))
plt.imshow(display_img)
plt.axis("off")
plt.show()

if prediction[0] == 0:
    print("Prediction: CAT")
else:
    print("Prediction: DOG")

